# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
  VERSION: "0.0.0"
  
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parallel_steps: [test, build]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Build
        if: matrix.parellel_steps == 'test'
        run: go build -v .
  
      - name: Tests
        if: matrix.parellel_steps == 'build'
        run: go test -v ./...
