# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
  
on: [push]

jobs:
  go:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.2'
          check-latest: true
      - name: Build
        run: go build -v .
  
      - name: Tests
        run: go test -v ./...
