# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go


env:
  VERSION: "0.0.0"
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Build
      run: |
        sed "s/x.x.x/${VERSION}/g" cmd/root.go
        go build -v ./...

    - name: Test
      run: |
        ./pauli --version
        go test -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: pauli
        path: ./pauli
	
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'main'

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: pauli
	path: .
